#!/usr/bin/env bash
set -euo pipefail

# Copies omarchy/hyprland/terminal configs into this repo, commits and
# pushes to GitHub. Run manually or via the systemd user timer.

# Under systemd there is no TTY and no agent, so make git fail fast rather
# than block forever on a passphrase or host-key prompt.
export GIT_TERMINAL_PROMPT=0
export GIT_SSH_COMMAND="${GIT_SSH_COMMAND:-ssh -oBatchMode=yes -oStrictHostKeyChecking=accept-new}"

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF="$HOME/.config"
DST="$REPO_DIR/home/.config"

info() { printf '\033[1;32m[dotfiles]\033[0m %s\n' "$*"; }

# Which machine is this? Per-host package tiers are generated from it.
# Write the id to ~/.dotfiles-host-id ("home", "tbtk", ...).
HOST="$(cat "$HOME/.dotfiles-host-id" 2>/dev/null || true)"
HOST="${HOST//[[:space:]]/}"
if [ -z "$HOST" ]; then
  info "no ~/.dotfiles-host-id found - skipping per-host package manifests"
  HOST=""
fi

# 1. Fresh copy so deleted files disappear from the repo too
rm -rf "$DST"
mkdir -p "$DST"

EXCLUDES=(
  --exclude='*.bak'
  --exclude='*.orig'
  --exclude='*.sample'
  --exclude='*~'
  --exclude='.git'
  # plugins/ are plain git clones; their repo URL + pinned commit live in
  # plugins.txt instead, so they are never committed as source.
  --exclude='plugins/'
  # ~/.config/omarchy/shell.toml is documented by omarchy as a machine-level
  # override (it is where `omarchy display text size` writes). It must not
  # travel between machines; theme-level <theme>/shell.toml still does.
  --exclude='/shell.toml'
  # Machine-local runtime state and stock assets, not user configuration:
  #   defaults/   e.g. the chosen agent, written by omarchy at runtime
  #   branding/   About/screensaver ASCII art, generated per install
  #   themed/     generated *.tpl.sample renderings
  --exclude='defaults/'
  --exclude='branding/'
  --exclude='themed/'
)

# Stock hook directories (hooks/*/) ship only *.sample files, which the
# excludes above drop, leaving empty dirs. git cannot track empty dirs
# anyway, so prune them rather than juggling rsync include rules.
prune_empty_dirs() { find "$DST" -mindepth 1 -type d -empty -delete 2>/dev/null || true; }

# Hyprland (bindings, monitors, input, looknfeel, ...)
rsync -a --delete "${EXCLUDES[@]}" "$CONF/hypr/" "$DST/hypr/"

# Omarchy: mirror the whole tree so subdirectory layout is preserved exactly.
#   extensions/omarchy-menu.jsonc  <- read by shell/plugins/menu/Menu.qml
#   themes/<name>/shell.toml        <- read by shell/Commons/Color.qml
#   hooks/post-update.d/*.hook
#   root-level *.json / *.jsonc     <- e.g. session-menu.jsonc
# Copying the tree (rather than a hand-picked file list) is what keeps new
# files from being silently dropped from the backup.
[ -d "$CONF/omarchy" ] && rsync -a --delete "${EXCLUDES[@]}" "$CONF/omarchy/" "$DST/omarchy/"

# Terminals
for t in alacritty kitty foot ghostty; do
  [ -d "$CONF/$t" ] && rsync -a --delete "${EXCLUDES[@]}" "$CONF/$t/" "$DST/$t/"
done

prune_empty_dirs

# 2. Installed plugin manifest: repo URL + checked-out commit
{
  printf '%-42s %-40s %s\n' "id" "commit" "repo"
  for dir in "$CONF"/omarchy/plugins/*/; do
    [ -d "$dir/.git" ] || continue
    id=$(basename "$dir")
    url=$(git -C "$dir" config --get remote.origin.url)
    commit=$(git -C "$dir" rev-parse HEAD)
    printf '%-42s %-40s %s\n' "$id" "$commit" "$url"
  done
} > "$REPO_DIR/plugins.txt"

# 3. Per-host package manifests (explicitly installed packages only).
#
# Only the tier for THIS machine is written, and it holds the DELTA against the
# shared tier -- packages this machine has that the shared tier does not.
# install-packages.sh reads shared + host, so the union reproduces this
# machine exactly while each file stays small and meaningful.
#
# packages-shared.txt and packages-shared-aur.txt are curated by hand and never
# regenerated here. That is deliberate: if the shared tier were rebuilt from
# whichever machine ran this script, syncing from the home PC would push its
# games into the shared tier and the work PC would then install them.
if [ -n "$HOST" ]; then
  # LC_ALL=C on every sort/comm so both sides collate bytewise identically.
  # Under a UTF-8 locale the shell and comm disagree on ordering for some
  # package sets and comm warns "file 1 is not in sorted order".
  host_repo() {
    LC_ALL=C comm -23 \
      <(pacman -Qqe | LC_ALL=C sort) \
      <(pacman -Qqm | LC_ALL=C sort)
  }
  host_aur() { pacman -Qqm | LC_ALL=C sort; }

  # Strip comments and blank lines so only real package names are compared.
  shared_names() {
    [ -f "$REPO_DIR/$1" ] || return 0
    grep -v '^[[:space:]]*#' "$REPO_DIR/$1" | grep -v '^[[:space:]]*$' | LC_ALL=C sort
  }

  {
    printf '# Packages unique to host %s (everything in packages-shared.txt is excluded).\n' "$HOST"
    printf '# Generated by sync-dotfiles.sh. Do not hand-edit; regenerate instead.\n'
    LC_ALL=C comm -23 <(host_repo) <(shared_names packages-shared.txt)
  } > "$REPO_DIR/packages-$HOST.txt"

  {
    printf '# AUR packages unique to host %s (shared AUR is excluded).\n' "$HOST"
    printf '# Generated by sync-dotfiles.sh. Do not hand-edit; regenerate instead.\n'
    LC_ALL=C comm -23 <(host_aur) <(shared_names packages-shared-aur.txt)
  } > "$REPO_DIR/packages-$HOST-aur.txt"

  count_pkgs() {
    local n
    n=$(grep -cv '^[[:space:]]*#\|^[[:space:]]*$' "$1" 2>/dev/null) || n=0
    printf '%s' "$n"
  }
  info "wrote package manifests for host '$HOST' ($(count_pkgs "$REPO_DIR/packages-$HOST.txt") unique repo, $(count_pkgs "$REPO_DIR/packages-$HOST-aur.txt") unique AUR)"
fi

# 4. Commit + push
cd "$REPO_DIR"
git add -A
if git diff --cached --quiet; then
  info "no changes, nothing to commit"
else
  git -c commit.gpgsign=false commit -q -m "backup: $(date '+%Y-%m-%d %H:%M')"
  info "committed"
fi
git push -q origin HEAD
info "pushed"